values:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/consumer.git
  branch: v1.3.0

project: ${PROJECT}
domainSuffix: ${DOMAINSUFFIX}
namespaceTag:
  consumer: ${NAMESPACETAG}
  authority: ${AUTHNAMESPACETAG}
  common: ${COMMONSPACETAG}

argocd:
  appname: ${NAMESPACE}
  namespace: argocd

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

hashicorp:
  service: "http://vault.namespace.svc.cluster.local:8200"
  secretEngine: ${SECRETENGINE}
  role: ${SECRETROLE}

keycloak:
  repo_URL: https://charts.bitnami.com/bitnami
  chart_name: keycloak
  targetRevision: 22.2.5
  nameOverride: keycloak
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

tier1_gateway:
  projectID: "772"
  targetRevision: 1.5.0
  chart_name: tier1-gateway
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

xfsc_advsearch_be:
  enabled: true
  projectID: "891"
  targetRevision: 1.9.1
  chart_name: xsfc-advsearch
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
  nameOverride: xfsc-advsearch-be

users_roles:
  projectID: "771"
  targetRevision: 1.5.0
  chart_name: users-roles
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

simpl_fe:
  projectID: "769"
  targetRevision: 1.5.2
  chart_name: simpl-fe
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-participant.yaml

tier2_gateway:
  projectID: "860"
  targetRevision: 1.5.0
  chart_name: tier2-gateway
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-routes.yaml

simpl_edc:
  enabled: true
  projectID: "920"
  targetRevision: 1.0.5
  chart_name: edc
  nameOverride: simpl-edc
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-consumer.yaml

edc_connector_adapter:
  enabled:  true
  projectID: "1091"
  targetRevision: 1.1.2
  chart_name: edc-connector-adapter
  nameOverride: edc-connector-adapter
  valueFiles:
    - values.yaml

simpl_catalogue_client:
  enabled: true
  projectID: "937"
  targetRevision: 1.2.0
  chart_name: catalogue-ui
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

auth_provider:
  projectID: "939"
  targetRevision: 1.5.0
  chart_name: authentication-provider
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

monitoring:
  enabled: true
  projectID: "828"
  targetRevision: 0.1.14
  chart_name: eck-monitoring
  fullnameOverride: elastic
  valueFiles:
    - values.yaml

contract:
  projectID: "872"
  targetRevision: 1.0.4
  chart_name: simpl-contract
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
  nameOverride: contract-consumer      

stubs:
  projectID: "930"
  targetRevision: 1.0.3
  chart_name: simpl-stubs
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml  

contract_consumption_be:
  enabled: true
  projectID: "968"
  targetRevision: 1.7.0
  chart_name: contract-consumption-be
  nameOverride: contract-consumption-be
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

simpl_cli:
  projectID: "882"
  targetRevision: 1.5.0
  chart_name: simpl-cli
  fullnameOverride: simpl-cli
  valueFiles:
    - values.yaml    

